name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          eval "$(ssh-agent -s)"
          ssh-add ssh_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i ssh_key.pem ubuntu@18.232.109.18 'cd /pockerhut-api && git pull && npm install && pm2 restart server.js'
        env:
          PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
